[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_example = "DjQNrS7m8ZBKnPuGU76kRnUzer2wz96kjMsj9fUbEVqX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
